version: '3.8'

services:
  mariadb:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: conserjeria123
      MYSQL_DATABASE: conserjeria
      MYSQL_USER: root
      MYSQL_PASSWORD: conserjeria123
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  conserjeria:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    ports:
      - "7071:7070"
    environment:
      DB_USERNAME: root
      DB_PASSWORD: conserjeria123
      DB_PLATFORM: mysql
      DB_DDL_MODE: dropCreate
      DB_NAME: conserjeria
      DB_URL: jdbc:mysql://mariadb:3306/conserjeria?useSSL=false&serverTimezone=UTC
volumes:
  mariadb_data: